//! The HTTP server + request dispatch.
//!
//! This mirrors the framework's `crates/cli/src/cmd_serve.rs` wiring: build a
//! template engine from `frontend/*.html`, load the `backend/page.json` context,
//! route through `backend/routes.json`, and render `content/**.md` into page
//! templates. The golf-specific content routes (news, handbook, legal) are
//! handled explicitly, the way the framework handles `/changelog` and `/docs/*`.
//!
//! Client-first and read-only for this foundation: static assets are served
//! directly, `/utilities.css` is generated by the atomic CSS engine, and dynamic
//! pages (booking calendar, shop, account, admin) render "coming soon"
//! placeholders. No database is touched yet — see PORT.md.

use crate::content;
use crate::mime;
use akurai_http::{
    MiddlewareStack, Reply, Request, RequestLogger, Response, SecurityHeaders, Server, Timing,
};
use akurai_json::Value;
use akurai_router::Router;
use akurai_template::Engine;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

const VERSION: &str = env!("CARGO_PKG_VERSION");

/// HTML and plain static assets revalidate on every request — they change on
/// deploy and must never be cached stale by a browser.
const NO_CACHE: &str = "no-cache";

pub struct Config {
    pub host: String,
    pub port: u16,
    /// The `frontend/` directory holding templates + static assets.
    pub dir: PathBuf,
}

/// Boot the server and serve until killed.
pub fn run(cfg: Config) -> io::Result<()> {
    if !cfg.dir.is_dir() {
        return Err(io::Error::new(
            io::ErrorKind::NotFound,
            format!("frontend directory not found: {}", cfg.dir.display()),
        ));
    }

    let addr = format!("{}:{}", cfg.host, cfg.port);
    let server = Server::bind(&addr)?;
    let local = server.local_addr()?;
    let root = cfg.dir.clone();

    println!("Golfsetrið Akureyri — golfsetridak v{VERSION} (on AkurAI-Framework)");
    println!("  serving {}", root.display());
    println!("  → http://{local}");
    println!("  utilities.css: served at /utilities.css");

    // Outermost first: security headers stamp every reply, then logging + timing.
    let middleware = MiddlewareStack::new()
        .push(SecurityHeaders)
        .push(RequestLogger)
        .push(Timing);

    server.run_with(middleware, move |req: &Request| {
        Reply::Response(dispatch(&root, req))
    })
}

/// Route one request to a buffered response. `root` is the `frontend/` dir.
fn dispatch(root: &Path, req: &Request) -> Response {
    let path = req.path.as_str();
    match path {
        "/utilities.css" => utilities(root),
        "/api/health" => json(200, &health()),

        // Markdown content pages — handled explicitly (mirrors the framework's
        // explicit `/changelog` and `/docs/*` routes).
        "/frettir" => news_list(root),
        p if p.starts_with("/frettir/") => news_detail(root, slug_of(p, "/frettir/")),
        "/notendahandbok" => handbook_list(root),
        p if p.starts_with("/notendahandbok/") => {
            handbook_detail(root, slug_of(p, "/notendahandbok/"))
        }
        "/personuvernd" => legal(root, "personuvernd"),
        "/skilmalar" => legal(root, "skilmalar"),
        "/um-okkur" => about(root),

        // Unknown API routes are a hard JSON 404, never an HTML fallback.
        p if p.starts_with("/api/") => json(404, &error_value("not found")),

        // Static assets (anything whose last segment has a non-`.html` extension).
        p if is_static_asset(p) => serve_static(root, p),

        // Everything else is a declarative page from routes.json (home +
        // placeholders for the dynamic pages that arrive in later phases).
        p => render_page_routed(root, p),
    }
}

// ---- content pages --------------------------------------------------------

fn news_list(root: &Path) -> Response {
    let items = content::news_items(&content_dir(root));
    render(
        root,
        "frettir",
        vec![
            ("page_title".into(), Value::Str("Fréttir".into())),
            ("news".into(), Value::Array(items)),
        ],
    )
}

fn news_detail(root: &Path, slug: &str) -> Response {
    if !valid_slug(slug) {
        return not_found_page(root);
    }
    let path = content_dir(root).join("frettir").join(format!("{slug}.md"));
    article(root, &path, "Fréttir")
}

fn handbook_list(root: &Path) -> Response {
    let chapters = content::handbook_chapters(&content_dir(root));
    render(
        root,
        "notendahandbok",
        vec![
            ("page_title".into(), Value::Str("Notendahandbók".into())),
            ("chapters".into(), Value::Array(chapters)),
        ],
    )
}

fn handbook_detail(root: &Path, slug: &str) -> Response {
    if !valid_slug(slug) {
        return not_found_page(root);
    }
    let path = content_dir(root)
        .join("notendahandbok")
        .join(format!("{slug}.md"));
    article(root, &path, "Notendahandbók")
}

fn legal(root: &Path, name: &str) -> Response {
    let path = content_dir(root).join("legal").join(format!("{name}.md"));
    article(root, &path, "")
}

fn about(root: &Path) -> Response {
    let path = content_dir(root).join("um-okkur.md");
    article(root, &path, "")
}

/// Render a single markdown article into the `article` template. The frontmatter
/// `title`/`date`/`lead`/`lastUpdated` populate the page; the body is converted
/// to HTML by `akurai_markdown`. A missing file renders the 404 page.
fn article(root: &Path, md_path: &Path, section: &str) -> Response {
    let raw = match fs::read_to_string(md_path) {
        Ok(text) => text,
        Err(_) => return not_found_page(root),
    };
    let doc = content::parse(&raw);
    let body_html = akurai_markdown::to_html(&doc.body);
    let title = doc.get("title").unwrap_or(section).to_string();

    let mut extra = vec![
        ("page_title".into(), Value::Str(title.clone())),
        ("title_text".into(), Value::Str(title)),
        ("section".into(), Value::Str(section.to_string())),
        ("content".into(), Value::Str(body_html)),
    ];
    if let Some(date) = doc.get("date") {
        extra.push(("date".into(), Value::Str(date.to_string())));
    }
    if let Some(lead) = doc.get("lead") {
        extra.push(("lead".into(), Value::Str(lead.to_string())));
    }
    if let Some(updated) = doc.get("lastUpdated") {
        extra.push(("last_updated".into(), Value::Str(updated.to_string())));
    }
    if let Some(desc) = doc.get("metaDescription") {
        extra.push(("meta_description".into(), Value::Str(desc.to_string())));
    }
    render(root, "article", extra)
}

// ---- declarative routed pages (home + placeholders) -----------------------

/// A resolved route: which template to render and an optional `backend/`-relative
/// JSON data file to merge into the context.
struct RouteDef {
    template: String,
    data: Option<String>,
    title: Option<String>,
}

fn render_page_routed(root: &Path, path: &str) -> Response {
    match load_routes(root) {
        Some(router) => match router.match_path(path) {
            Some(m) => render_routed(root, m.value, &m.params),
            None => not_found_page(root),
        },
        None => not_found_page(root),
    }
}

fn render_routed(root: &Path, def: &RouteDef, params: &[(String, String)]) -> Response {
    let mut extra: Vec<(String, Value)> = Vec::new();

    // Per-route data file: spread its top-level object keys into the context
    // (the framework's data-loader convention), skipping the reserved `params`.
    if let Some(rel) = &def.data {
        if let Some(Value::Object(pairs)) = load_route_data(root, rel) {
            for (k, v) in pairs {
                if k != "params" {
                    extra.push((k, v));
                }
            }
        }
    }

    // Page title: a `heading` from the data file wins, else the route's SEO title.
    let page_title = extra
        .iter()
        .find(|(k, _)| k == "heading")
        .and_then(|(_, v)| v.as_str().map(str::to_string))
        .or_else(|| def.title.clone());
    if let Some(title) = page_title {
        extra.push(("page_title".into(), Value::Str(title)));
    }

    extra.push(("params".into(), params_value(params)));
    render(root, &def.template, extra)
}

/// Load `backend/routes.json` into a router. Mirrors the framework's `routes.rs`
/// but only reads the fields this app uses (`template`, `data`, `title`).
fn load_routes(root: &Path) -> Option<Router<RouteDef>> {
    let path = root.parent()?.join("backend/routes.json");
    let text = fs::read_to_string(path).ok()?;
    let value = akurai_json::parse(&text).ok()?;
    let Value::Array(entries) = value.get("routes")? else {
        return None;
    };
    let mut router = Router::new();
    let mut any = false;
    for entry in entries {
        if let (Some(pattern), Some(template)) = (
            entry.get("path").and_then(Value::as_str),
            entry.get("template").and_then(Value::as_str),
        ) {
            router.route(
                pattern,
                RouteDef {
                    template: template.to_string(),
                    data: entry.get("data").and_then(Value::as_str).map(String::from),
                    title: entry.get("title").and_then(Value::as_str).map(String::from),
                },
            );
            any = true;
        }
    }
    any.then_some(router)
}

/// Load and parse a `backend/`-relative JSON data file, rejecting path traversal.
fn load_route_data(root: &Path, rel: &str) -> Option<Value> {
    let rel = rel.trim_start_matches('/');
    if rel.is_empty() || rel.split('/').any(|seg| seg == ".." || seg == ".") {
        return None;
    }
    let path = root.parent()?.join("backend").join(rel);
    let text = fs::read_to_string(path).ok()?;
    akurai_json::parse(&text).ok()
}

fn params_value(params: &[(String, String)]) -> Value {
    Value::Object(
        params
            .iter()
            .map(|(k, v)| (k.clone(), Value::Str(v.clone())))
            .collect(),
    )
}

// ---- rendering core -------------------------------------------------------

/// Render template `name` with the `page.json` context plus `extra` pairs. A
/// template or parse error surfaces as a 500 so it is visible in development.
fn render(root: &Path, name: &str, extra: Vec<(String, Value)>) -> Response {
    let engine = match build_engine(root) {
        Ok(engine) => engine,
        Err(msg) => return Response::new(500).with_html(&error_page(&msg)),
    };
    let mut context = load_context(root);
    if let Value::Object(pairs) = &mut context {
        pairs.extend(extra);
    }
    match engine.render(name, &context) {
        Ok(html) => with_no_cache(Response::ok().with_html(&html)),
        Err(e) => Response::new(500).with_html(&error_page(&e.message)),
    }
}

/// Render the 404 page (status 404). Falls back to a bare body if the template
/// itself is missing or broken.
fn not_found_page(root: &Path) -> Response {
    let mut resp = render(
        root,
        "notfound",
        vec![("page_title".into(), Value::Str("Síða finnst ekki".into()))],
    );
    if resp.status == 200 {
        resp.status = 404;
    }
    resp
}

/// Register every `frontend/*.html` as a template keyed by file stem.
fn build_engine(root: &Path) -> Result<Engine, String> {
    let mut engine = Engine::new();
    let entries = fs::read_dir(root).map_err(|e| format!("cannot read {}: {e}", root.display()))?;
    for entry in entries {
        let path = entry.map_err(|e| e.to_string())?.path();
        if path.extension().and_then(|e| e.to_str()) != Some("html") {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        let source = fs::read_to_string(&path).map_err(|e| e.to_string())?;
        engine
            .register(stem, &source)
            .map_err(|e| format!("{stem}.html: {}", e.message))?;
    }
    Ok(engine)
}

/// Load the shared page context from `backend/page.json`, or an empty object.
fn load_context(root: &Path) -> Value {
    let empty = Value::Object(vec![]);
    let Some(path) = root.parent().map(|p| p.join("backend/page.json")) else {
        return empty;
    };
    match fs::read_to_string(&path) {
        Ok(text) => akurai_json::parse(&text).unwrap_or(empty),
        Err(_) => empty,
    }
}

/// The project's `content/` dir, a sibling of `frontend/`.
fn content_dir(root: &Path) -> PathBuf {
    root.parent()
        .map(|p| p.join("content"))
        .unwrap_or_else(|| root.join("content"))
}

// ---- static assets + CSS engine -------------------------------------------

/// Generate `utilities.css` by scanning frontend source for utility classes.
fn utilities(root: &Path) -> Response {
    let mut files = Vec::new();
    collect_sources(root, &mut files);
    files.sort();
    let sources: Vec<String> = files
        .iter()
        .filter_map(|p| fs::read_to_string(p).ok())
        .collect();
    let refs: Vec<&str> = sources.iter().map(String::as_str).collect();
    let css = akurai_css::build(&refs);
    with_no_cache(Response::ok().with_body("text/css; charset=utf-8", css.into_bytes()))
}

/// Recursively collect scannable frontend source files (HTML/JS) under `dir`.
fn collect_sources(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let Ok(meta) = entry.metadata() else { continue };
        if meta.is_dir() {
            collect_sources(&path, out);
        } else if matches!(
            path.extension().and_then(|e| e.to_str()),
            Some("html") | Some("htm") | Some("js") | Some("mjs")
        ) {
            out.push(path);
        }
    }
}

fn serve_static(root: &Path, req_path: &str) -> Response {
    match resolve(root, req_path) {
        Some(path) if path.is_file() => match fs::read(&path) {
            Ok(bytes) => with_no_cache(
                Response::ok().with_body(mime::for_path(&path.to_string_lossy()), bytes),
            ),
            Err(_) => Response::not_found(),
        },
        _ => Response::not_found(),
    }
}

/// Map a request path to a file under `root`, rejecting traversal (`..`/`.`).
fn resolve(root: &Path, req_path: &str) -> Option<PathBuf> {
    let rel = req_path.trim_start_matches('/');
    let rel = if rel.is_empty() { "index.html" } else { rel };
    if rel.split('/').any(|seg| seg == ".." || seg == ".") {
        return None;
    }
    Some(root.join(rel))
}

/// A request is a static asset if its last segment has a non-`.html` extension.
fn is_static_asset(path: &str) -> bool {
    let last = path.rsplit('/').next().unwrap_or("");
    match last.rsplit_once('.') {
        Some((_, ext)) => !ext.eq_ignore_ascii_case("html"),
        None => false,
    }
}

// ---- helpers --------------------------------------------------------------

/// Extract a single-segment slug after `prefix` (drops a trailing slash).
fn slug_of<'a>(path: &'a str, prefix: &str) -> &'a str {
    path.strip_prefix(prefix)
        .unwrap_or("")
        .trim_end_matches('/')
}

/// A safe content slug: non-empty, no path separators, ASCII word/`-` only.
fn valid_slug(slug: &str) -> bool {
    !slug.is_empty()
        && slug
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
}

fn with_no_cache(resp: Response) -> Response {
    resp.with_header("Cache-Control", NO_CACHE)
}

fn json(status: u16, value: &Value) -> Response {
    Response::new(status).with_body(
        "application/json; charset=utf-8",
        value.to_json().into_bytes(),
    )
}

fn health() -> Value {
    Value::Object(vec![
        ("app".into(), Value::Str("golfsetridak".into())),
        ("framework".into(), Value::Str("AkurAI-Framework".into())),
        ("version".into(), Value::Str(VERSION.into())),
        ("status".into(), Value::Str("ok".into())),
    ])
}

fn error_value(message: &str) -> Value {
    Value::Object(vec![("error".into(), Value::Str(message.into()))])
}

fn error_page(message: &str) -> String {
    let mut escaped = String::new();
    for c in message.chars() {
        match c {
            '<' => escaped.push_str("&lt;"),
            '>' => escaped.push_str("&gt;"),
            '&' => escaped.push_str("&amp;"),
            c => escaped.push(c),
        }
    }
    format!(
        "<!doctype html><meta charset=utf-8><title>Template error</title>\
         <body style=\"font:16px system-ui;background:#0a0f0c;color:#ff6b6b;padding:40px\">\
         <h1>Template error</h1><pre style=\"color:#e9efe9\">{escaped}</pre></body>"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn slug_extraction_and_validation() {
        assert_eq!(slug_of("/frettir/abc-1", "/frettir/"), "abc-1");
        assert_eq!(slug_of("/frettir/abc/", "/frettir/"), "abc");
        assert!(valid_slug("6-7-payday-bokhald-og-vsk"));
        assert!(!valid_slug(""));
        assert!(!valid_slug("../etc/passwd"));
        assert!(!valid_slug("a/b"));
    }

    #[test]
    fn static_asset_detection() {
        assert!(is_static_asset("/styles.css"));
        assert!(is_static_asset("/img/logo.svg"));
        assert!(!is_static_asset("/frettir"));
        assert!(!is_static_asset("/index.html"));
    }

    #[test]
    fn resolve_rejects_traversal() {
        assert!(resolve(Path::new("/srv"), "/../../etc/passwd").is_none());
        assert!(resolve(Path::new("/srv"), "/ok/app.js").is_some());
        assert!(resolve(Path::new("/srv"), "/")
            .unwrap()
            .ends_with("index.html"));
    }

    #[test]
    fn route_data_rejects_traversal() {
        assert!(load_route_data(Path::new("/srv/frontend"), "../secrets.json").is_none());
        assert!(load_route_data(Path::new("/srv/frontend"), "").is_none());
        assert!(load_route_data(Path::new("/srv/frontend"), "data/missing.json").is_none());
    }

    #[test]
    fn health_reports_ok() {
        let v = health();
        assert_eq!(v.get("status").and_then(Value::as_str), Some("ok"));
        assert_eq!(v.get("app").and_then(Value::as_str), Some("golfsetridak"));
    }
}
