//! The HTTP server + request dispatch.
//!
//! This mirrors the framework's `crates/cli/src/cmd_serve.rs` wiring: build a
//! template engine from `frontend/*.html`, load the `backend/page.json` context,
//! route through `backend/routes.json`, and render `content/**.md` into page
//! templates. The golf-specific content routes (news, handbook, legal) are
//! handled explicitly, the way the framework handles `/changelog` and `/docs/*`.
//!
//! Static assets are served directly and `/utilities.css` is generated by the
//! atomic CSS engine. The Phase-3 booking engine adds a server-rendered booking
//! calendar at `/` plus the JSON booking API (`/api/availability`,
//! `/api/slot-price`, `/api/book`, `/api/bookings`) backed by [`booking::Store`].
//! The remaining dynamic pages (shop, account, admin) still render "coming soon"
//! placeholders — see PORT.md.

use crate::auth;
use crate::booking::{self, Store as BookingStore};
use crate::cart::{self, Store as CartStore};
use crate::content;
use crate::mime;
use crate::shop::{self, Store as ShopStore};
use akurai_http::form::{field, parse_urlencoded};
use akurai_http::{
    Method, MiddlewareStack, Reply, Request, RequestLogger, Response, SecurityHeaders, Server,
    Timing,
};
use akurai_json::Value;
use akurai_router::Router;
use akurai_template::Engine;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::time::{SystemTime, UNIX_EPOCH};

const VERSION: &str = env!("CARGO_PKG_VERSION");

/// HTML and plain static assets revalidate on every request — they change on
/// deploy and must never be cached stale by a browser.
const NO_CACHE: &str = "no-cache";

pub struct Config {
    pub host: String,
    pub port: u16,
    /// The `frontend/` directory holding templates + static assets.
    pub dir: PathBuf,
}

/// Boot the server and serve until killed.
pub fn run(cfg: Config) -> io::Result<()> {
    if !cfg.dir.is_dir() {
        return Err(io::Error::new(
            io::ErrorKind::NotFound,
            format!("frontend directory not found: {}", cfg.dir.display()),
        ));
    }

    let addr = format!("{}:{}", cfg.host, cfg.port);
    let server = Server::bind(&addr)?;
    let local = server.local_addr()?;
    let root = cfg.dir.clone();

    // The booking database lives alongside the app dir (sibling of `frontend/`),
    // in `data/booking/`. Gitignored — never committed (see .gitignore).
    let data_dir = data_dir(&root);
    let store = Arc::new(BookingStore::open(&data_dir)?);
    let shop_store = Arc::new(ShopStore::open(&shop_data_dir(&root))?);
    let cart_store = Arc::new(CartStore::open(&cart_data_dir(&root))?);

    // Auth stores live under data/auth/ (sibling of data/booking/).
    let auth_data = data_dir
        .parent()
        .map(|p| p.join("auth"))
        .unwrap_or_else(|| data_dir.join("auth"));
    let auth = Arc::new(auth::State::open(&auth_data)?);

    println!("Golfsetrið Akureyri — golfsetridak v{VERSION} (on AkurAI-Framework)");
    println!("  serving {}", root.display());
    println!("  booking db: {}", data_dir.display());
    println!("  shop db: {}", shop_data_dir(&root).display());
    println!("  cart db: {}", cart_data_dir(&root).display());
    println!("  → http://{local}");
    println!("  utilities.css: served at /utilities.css");

    // Outermost first: security headers stamp every reply, then logging + timing.
    let middleware = MiddlewareStack::new()
        .push(SecurityHeaders)
        .push(RequestLogger)
        .push(Timing);

    server.run_with(middleware, move |req: &Request| {
        dispatch_reply(&root, &store, &shop_store, &cart_store, &auth, req)
    })
}

/// Current wall-clock time as epoch-milliseconds (UTC).
fn now_ms() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as i64)
        .unwrap_or(0)
}

/// Resolve the booking database directory for a given `frontend/` dir: a
/// `data/booking/` sibling of the app dir. Shared by `serve` and `seed-demo`.
pub fn data_dir(frontend_dir: &Path) -> PathBuf {
    frontend_dir
        .parent()
        .map(|p| p.join("data/booking"))
        .unwrap_or_else(|| frontend_dir.join("data/booking"))
}

fn shop_data_dir(frontend_dir: &Path) -> PathBuf {
    frontend_dir
        .parent()
        .map(|p| p.join("data/shop"))
        .unwrap_or_else(|| frontend_dir.join("data/shop"))
}

fn cart_data_dir(frontend_dir: &Path) -> PathBuf {
    frontend_dir
        .parent()
        .map(|p| p.join("data/cart"))
        .unwrap_or_else(|| frontend_dir.join("data/cart"))
}

/// Seed a demo user, a klippikort package grant (`slots` slots) and an active
/// subscription, so package/subscription bookings can be exercised before the
/// purchase/admin flows (other agents' scope) land. Mirrors the source's
/// `seed.ts` / `seed-demo.ts`. Idempotent: re-running overwrites the same ids.
pub fn seed_demo(frontend_dir: &Path, slots: i64) -> io::Result<()> {
    let store = BookingStore::open(&data_dir(frontend_dir))?;
    let now = now_ms();
    let today = booking::time::day_start(now);

    // A standard demo customer and a fixed-price (VIP) customer.
    store.put_user("demo", None)?;
    store.put_user("vip", Some(1000))?;

    // A klippikort grant with `slots` remaining slots.
    store.put_user_package(&booking::UserPackage {
        id: "demo-pkg".into(),
        user_id: "demo".into(),
        remaining: slots,
        package_name: Some("Demo Package".into()),
        slot_count: Some(slots),
    })?;

    // An active subscription window (yesterday → +60 days), limit 2/day.
    store.put_user_subscription(&booking::UserSubscription {
        id: "demo-sub".into(),
        user_id: "demo".into(),
        valid_from: booking::time::add_days(today, -1),
        valid_until: booking::time::add_days(today, 60),
        daily_limit: 2,
    })?;

    let remaining = store
        .user_package("demo-pkg")
        .map(|p| p.remaining)
        .unwrap_or(0);
    println!("Seeded demo data into {}", data_dir(frontend_dir).display());
    println!("  user        demo  (no fixed price)");
    println!("  user        vip   (fixed price 1000)");
    println!("  package     demo-pkg  remaining={remaining}");
    println!("  subscription demo-sub  daily_limit=2 (active 61 days)");
    Ok(())
}

/// Top-level reply dispatcher — handles auth routes before content routes.
fn dispatch_reply(
    root: &Path,
    store: &BookingStore,
    shop_store: &ShopStore,
    cart_store: &CartStore,
    auth: &auth::State,
    req: &Request,
) -> Reply {
    let path = req.path.as_str();
    match path {
        "/login" => auth::login(auth, root, req, store),
        "/logout" => auth::logout(auth, req),
        _ => Reply::Response(dispatch(root, store, shop_store, cart_store, auth, req)),
    }
}

/// Route one request to a buffered response. `root` is the `frontend/` dir.
fn dispatch(
    root: &Path,
    store: &BookingStore,
    shop_store: &ShopStore,
    cart_store: &CartStore,
    auth: &auth::State,
    req: &Request,
) -> Response {
    let path = req.path.as_str();
    match path {
        "/utilities.css" => utilities(root),
        "/api/health" => json(200, &health()),
        "/api/me" => api_me(auth, req),
        "/api/user-packages" => api_user_packages(store, auth, req),

        // Booking API (Phase 3). Methods are checked inside each handler.
        "/api/availability" => api_availability(store, req, auth),
        "/api/slot-price" => api_slot_price(store, req, auth),
        "/api/book" => api_book(store, req, auth),
        "/api/bookings" => api_bookings(store, req, auth),
        "/api/shop/products" => api_shop_products(shop_store, req),
        "/api/shop/categories" => api_shop_categories(shop_store, req),
        "/api/admin/shop/products" => {
            if !auth.require_role(req, auth::Role::Admin) {
                return json(401, &error_value("Unauthorized"));
            }
            api_admin_products(shop_store, req, None)
        }
        "/api/admin/shop/categories" => {
            if !auth.require_role(req, auth::Role::Admin) {
                return json(401, &error_value("Unauthorized"));
            }
            api_admin_categories(shop_store, req, None)
        }
        "/api/cart" => api_cart(cart_store, req, auth),
        "/api/cart/items" => api_cart_items(store, shop_store, cart_store, req, None, auth),
        "/api/cart/items/bulk" => api_cart_items_bulk(store, shop_store, cart_store, req, auth),
        p if p.starts_with("/api/admin/shop/products/") => {
            if !auth.require_role(req, auth::Role::Admin) {
                return json(401, &error_value("Unauthorized"));
            }
            api_admin_products(
                shop_store,
                req,
                Some(slug_of(p, "/api/admin/shop/products/")),
            )
        }
        p if p.starts_with("/api/admin/shop/categories/") => {
            if !auth.require_role(req, auth::Role::Admin) {
                return json(401, &error_value("Unauthorized"));
            }
            api_admin_categories(
                shop_store,
                req,
                Some(slug_of(p, "/api/admin/shop/categories/")),
            )
        }
        p if p.starts_with("/api/cart/items/") => api_cart_items(
            store,
            shop_store,
            cart_store,
            req,
            Some(slug_of(p, "/api/cart/items/")),
            auth,
        ),

        // Home: the server-rendered booking calendar (replaces the placeholder).
        "/" => calendar_page(root, store, auth, req),

        // Markdown content pages — handled explicitly (mirrors the framework's
        // explicit `/changelog` and `/docs/*` routes).
        "/frettir" => news_list(root, auth, req),
        p if p.starts_with("/frettir/") => news_detail(root, slug_of(p, "/frettir/"), auth, req),
        "/notendahandbok" => handbook_list(root, auth, req),
        p if p.starts_with("/notendahandbok/") => {
            handbook_detail(root, slug_of(p, "/notendahandbok/"), auth, req)
        }
        "/personuvernd" => legal(root, "personuvernd", auth, req),
        "/skilmalar" => legal(root, "skilmalar", auth, req),
        "/um-okkur" => about(root, auth, req),
        "/verslun" => shop_page(root, shop_store, auth, req),
        "/my" => my_page(root, store, auth, req),
        "/my/verslun" => shop_page(root, shop_store, auth, req),
        "/my/verslun/karfa" => cart_page(root, cart_store, req, auth),
        "/admin/vorur" => {
            if !auth.require_role(req, auth::Role::Admin) {
                return Response::new(302).with_header("Location", "/login");
            }
            admin_products_page(root, shop_store, auth, req)
        }
        "/admin/vorur/flokkar" => {
            if !auth.require_role(req, auth::Role::Admin) {
                return Response::new(302).with_header("Location", "/login");
            }
            admin_categories_page(root, shop_store, auth, req)
        }
        "/admin/vorur/nytt" => {
            if !auth.require_role(req, auth::Role::Admin) {
                return Response::new(302).with_header("Location", "/login");
            }
            admin_product_form_page(root, shop_store, None, auth, req)
        }
        p if p.starts_with("/admin/vorur/") => {
            if !auth.require_role(req, auth::Role::Admin) {
                return Response::new(302).with_header("Location", "/login");
            }
            admin_product_form_page(
                root,
                shop_store,
                Some(slug_of(p, "/admin/vorur/")),
                auth,
                req,
            )
        }

        // Unknown API routes are a hard JSON 404, never an HTML fallback.
        p if p.starts_with("/api/") => json(404, &error_value("not found")),

        // Static assets (anything whose last segment has a non-`.html` extension).
        p if is_static_asset(p) => serve_static(root, p),

        // Everything else is a declarative page from routes.json (the remaining
        // placeholders for the dynamic pages that arrive in later phases).
        p => render_page_routed(root, p, auth, req),
    }
}

// ---- booking API ----------------------------------------------------------

/// Parse the request query string into `(key, value)` pairs.
fn query_pairs(req: &Request) -> Vec<(String, String)> {
    req.query
        .as_deref()
        .map(parse_urlencoded)
        .unwrap_or_default()
}

/// Resolve the acting user id from the session cookie.
///
/// The session email is the stable user id used by the booking store. Returns
/// `None` when unauthenticated, causing the booking APIs to respond with 401.
fn resolve_user_id(req: &Request, _body: Option<&Value>, auth: &auth::State) -> Option<String> {
    auth.current_user(req).map(|u| u.email)
}

/// `GET /api/availability?date=YYYY-MM-DD&days=N&userId=X` — slots + prices.
fn api_availability(store: &BookingStore, req: &Request, auth: &auth::State) -> Response {
    if req.method != Method::Get {
        return json(405, &error_value("method not allowed"));
    }
    let q = query_pairs(req);
    let now = now_ms();
    let start = match field(&q, "date") {
        Some(d) => match booking::time::parse_date(d) {
            Some(ms) => ms,
            None => return json(400, &error_value("Invalid date")),
        },
        None => booking::time::day_start(now),
    };
    // Clamp days to 1..=30, matching the source route.
    let days = field(&q, "days")
        .and_then(|s| s.parse::<i64>().ok())
        .unwrap_or(7)
        .clamp(1, 30);
    let user = resolve_user_id(req, None, auth);
    let availability = store.availability(start, days, user.as_deref(), now);
    json(200, &availability_value(&availability))
}

/// `GET /api/slot-price?hour=H&userId=X` — the effective price for an hour.
fn api_slot_price(store: &BookingStore, req: &Request, auth: &auth::State) -> Response {
    if req.method != Method::Get {
        return json(405, &error_value("method not allowed"));
    }
    let q = query_pairs(req);
    let hour = field(&q, "hour").and_then(|s| s.parse::<i64>().ok());
    let Some(hour) = hour.filter(|h| (0..=23).contains(h)) else {
        return json(400, &error_value("hour must be 0-23"));
    };
    let user = resolve_user_id(req, None, auth);
    let price = store.slot_price(hour, user.as_deref());
    json(
        200,
        &Value::Object(vec![("price".into(), Value::Int(price))]),
    )
}

/// `POST /api/book` — create a booking. Body: `{ userId, slotTime, paymentType,
/// userPackageId?, userSubscriptionId?, notes? }`.
fn api_book(store: &BookingStore, req: &Request, auth: &auth::State) -> Response {
    if req.method != Method::Post {
        return json(405, &error_value("method not allowed"));
    }
    let body = match akurai_json::parse(&req.body_str()) {
        Ok(v) => v,
        Err(_) => return json(400, &error_value("invalid JSON body")),
    };

    let Some(user_id) = resolve_user_id(req, Some(&body), auth) else {
        return json(401, &error_value("Unauthorized"));
    };

    let payment_type = body.get("paymentType").and_then(Value::as_str);
    let slot_raw = body.get("slotTime");
    let (Some(payment_type), Some(slot_raw)) = (payment_type, slot_raw) else {
        return json(400, &error_value("slotTime and paymentType are required"));
    };
    // slotTime may arrive as an ISO string or an integer epoch-ms.
    let slot_ms = match slot_raw {
        Value::Int(ms) => Some(*ms),
        Value::Str(s) => booking::time::parse_instant(s),
        _ => None,
    };
    let Some(slot_ms) = slot_ms else {
        return json(400, &error_value("Invalid slotTime"));
    };

    let now = now_ms();
    let has_package = payment_type == "package";
    if let Err(e) = booking::validation::validate_booking_request(slot_ms, has_package, now) {
        return json(400, &error_value(&e));
    }

    let ref_id = if payment_type == "subscription" {
        body.get("userSubscriptionId").and_then(Value::as_str)
    } else {
        body.get("userPackageId").and_then(Value::as_str)
    };
    let notes = body.get("notes").and_then(Value::as_str);

    match store.create_booking(&user_id, slot_ms, payment_type, ref_id, notes, now) {
        Ok(id) => json(
            200,
            &Value::Object(vec![(
                "booking".into(),
                Value::Object(vec![("bookingId".into(), Value::Str(id))]),
            )]),
        ),
        Err(e) => json(400, &error_value(&e)),
    }
}

/// `GET /api/bookings?userId=X` lists a user's bookings;
/// `DELETE /api/bookings?id=B&userId=X` cancels one.
fn api_bookings(store: &BookingStore, req: &Request, auth: &auth::State) -> Response {
    let q = query_pairs(req);
    match req.method {
        Method::Get => {
            let Some(user_id) = resolve_user_id(req, None, auth) else {
                return json(401, &error_value("Unauthorized"));
            };
            let list: Vec<Value> = store
                .bookings_for_user(&user_id)
                .iter()
                .map(booking_value)
                .collect();
            json(
                200,
                &Value::Object(vec![("bookings".into(), Value::Array(list))]),
            )
        }
        Method::Delete => {
            let Some(user_id) = resolve_user_id(req, None, auth) else {
                return json(401, &error_value("Unauthorized"));
            };
            let Some(id) = field(&q, "id").filter(|s| !s.is_empty()) else {
                return json(400, &error_value("id is required"));
            };
            match store.cancel_booking(id, &user_id, now_ms()) {
                Ok(()) => json(
                    200,
                    &Value::Object(vec![("cancelled".into(), Value::Bool(true))]),
                ),
                Err(e) => json(400, &error_value(&e)),
            }
        }
        _ => json(405, &error_value("method not allowed")),
    }
}

/// Serialize availability into the `{ availability: [...] }` JSON the source
/// route returns.
fn availability_value(days: &[booking::DayAvailability]) -> Value {
    let arr = days
        .iter()
        .map(|day| {
            let slots = day
                .slots
                .iter()
                .map(|s| {
                    Value::Object(vec![
                        ("hour".into(), Value::Int(s.hour)),
                        ("startsAt".into(), Value::Str(s.starts_at.clone())),
                        ("price".into(), Value::Int(s.price)),
                        ("status".into(), Value::Str(s.status.clone())),
                    ])
                })
                .collect();
            Value::Object(vec![
                ("date".into(), Value::Str(day.date.clone())),
                ("slots".into(), Value::Array(slots)),
            ])
        })
        .collect();
    Value::Object(vec![("availability".into(), Value::Array(arr))])
}

/// Serialize one booking record to JSON (camelCase, mirroring the source API).
fn booking_value(b: &booking::Booking) -> Value {
    let opt_str = |o: &Option<String>| o.clone().map(Value::Str).unwrap_or(Value::Null);
    let opt_int = |o: Option<i64>| o.map(Value::Int).unwrap_or(Value::Null);
    Value::Object(vec![
        ("id".into(), Value::Str(b.id.clone())),
        ("userId".into(), Value::Str(b.user_id.clone())),
        (
            "startsAt".into(),
            Value::Str(booking::time::iso_string(b.starts_at)),
        ),
        ("status".into(), Value::Str(b.status.clone())),
        ("paymentType".into(), Value::Str(b.payment_type.clone())),
        ("pricePaid".into(), opt_int(b.price_paid)),
        ("userPackageId".into(), opt_str(&b.user_package_id)),
        (
            "userSubscriptionId".into(),
            opt_str(&b.user_subscription_id),
        ),
        ("notes".into(), opt_str(&b.notes)),
    ])
}

// ---- shop + cart API ------------------------------------------------------

fn api_shop_products(store: &ShopStore, req: &Request) -> Response {
    if req.method != Method::Get {
        return json(405, &error_value("method not allowed"));
    }
    json(
        200,
        &Value::Object(vec![(
            "products".into(),
            Value::Array(product_values(store, true)),
        )]),
    )
}

fn api_shop_categories(store: &ShopStore, req: &Request) -> Response {
    if req.method != Method::Get {
        return json(405, &error_value("method not allowed"));
    }
    let rows = store
        .list_categories(false)
        .iter()
        .map(shop::category_value)
        .collect();
    json(
        200,
        &Value::Object(vec![("categories".into(), Value::Array(rows))]),
    )
}

fn api_admin_products(store: &ShopStore, req: &Request, path_id: Option<&str>) -> Response {
    match req.method {
        Method::Get => {
            if let Some(id) = path_id {
                return match store.product(id) {
                    Some(product) => json(
                        200,
                        &Value::Object(vec![(
                            "product".into(),
                            shop::product_value(
                                &product,
                                store.category_name(product.category_id.as_deref()),
                            ),
                        )]),
                    ),
                    None => json(404, &error_value("not found")),
                };
            }
            json(
                200,
                &Value::Object(vec![(
                    "products".into(),
                    Value::Array(product_values(store, false)),
                )]),
            )
        }
        Method::Post => {
            let body = match body_json(req) {
                Ok(v) => v,
                Err(r) => return r,
            };
            let Some(name) = str_field(&body, "name") else {
                return json(400, &error_value("name required"));
            };
            let Some(price) = int_field(&body, "price") else {
                return json(400, &error_value("valid price required"));
            };
            let now = now_ms();
            match store.create_product(
                shop::ProductDraft {
                    name,
                    description: str_field(&body, "description"),
                    price,
                    image_url: str_field(&body, "imageUrl")
                        .or_else(|| str_field(&body, "image_url")),
                    category_id: str_field(&body, "categoryId")
                        .or_else(|| str_field(&body, "category_id")),
                    active: bool_field(&body, "active").unwrap_or(true),
                },
                now,
            ) {
                Ok(product) => json(
                    201,
                    &Value::Object(vec![(
                        "product".into(),
                        shop::product_value(
                            &product,
                            store.category_name(product.category_id.as_deref()),
                        ),
                    )]),
                ),
                Err(e) => json(400, &error_value(&e)),
            }
        }
        Method::Put => {
            let body = match body_json(req) {
                Ok(v) => v,
                Err(r) => return r,
            };
            let query_id = query_id(req);
            let Some(id) = path_id
                .or_else(|| str_field(&body, "id"))
                .or(query_id.as_deref())
            else {
                return json(400, &error_value("id required"));
            };
            let update = shop::ProductUpdate {
                name: str_field(&body, "name").map(str::to_string),
                description: field_present(&body, "description")
                    .then(|| str_field(&body, "description").map(str::to_string)),
                price: int_field(&body, "price"),
                image_url: field_present(&body, "imageUrl")
                    .then(|| str_field(&body, "imageUrl").map(str::to_string)),
                category_id: field_present(&body, "categoryId")
                    .then(|| str_field(&body, "categoryId").map(str::to_string)),
                active: bool_field(&body, "active"),
                position: int_field(&body, "position"),
            };
            match store.update_product(id, update, now_ms()) {
                Ok(product) => json(
                    200,
                    &Value::Object(vec![(
                        "product".into(),
                        shop::product_value(
                            &product,
                            store.category_name(product.category_id.as_deref()),
                        ),
                    )]),
                ),
                Err(e) if e == "not found" => json(404, &error_value(&e)),
                Err(e) => json(400, &error_value(&e)),
            }
        }
        Method::Delete => {
            let body = body_json(req).ok();
            let query_id = query_id(req);
            let id = path_id
                .or_else(|| body.as_ref().and_then(|b| str_field(b, "id")))
                .or(query_id.as_deref());
            let Some(id) = id else {
                return json(400, &error_value("id required"));
            };
            match store.delete_product(id) {
                Ok(()) => json(200, &Value::Object(vec![("ok".into(), Value::Bool(true))])),
                Err(e) if e == "not found" => json(404, &error_value(&e)),
                Err(e) => json(400, &error_value(&e)),
            }
        }
        _ => json(405, &error_value("method not allowed")),
    }
}

fn api_admin_categories(store: &ShopStore, req: &Request, path_id: Option<&str>) -> Response {
    match req.method {
        Method::Get => {
            if let Some(id) = path_id {
                return match store.category(id) {
                    Some(category) => json(
                        200,
                        &Value::Object(vec![("category".into(), shop::category_value(&category))]),
                    ),
                    None => json(404, &error_value("not found")),
                };
            }
            let rows = store
                .list_categories(false)
                .iter()
                .map(shop::category_value)
                .collect();
            json(
                200,
                &Value::Object(vec![("categories".into(), Value::Array(rows))]),
            )
        }
        Method::Post => {
            let body = match body_json(req) {
                Ok(v) => v,
                Err(r) => return r,
            };
            let Some(name) = str_field(&body, "name") else {
                return json(400, &error_value("name required"));
            };
            match store.create_category(
                name,
                str_field(&body, "slug"),
                str_field(&body, "description"),
                int_field(&body, "position").unwrap_or(0),
                bool_field(&body, "active").unwrap_or(true),
                now_ms(),
            ) {
                Ok(category) => json(
                    201,
                    &Value::Object(vec![("category".into(), shop::category_value(&category))]),
                ),
                Err(e) => json(400, &error_value(&e)),
            }
        }
        Method::Put => {
            let body = match body_json(req) {
                Ok(v) => v,
                Err(r) => return r,
            };
            let query_id = query_id(req);
            let Some(id) = path_id
                .or_else(|| str_field(&body, "id"))
                .or(query_id.as_deref())
            else {
                return json(400, &error_value("id required"));
            };
            let update = shop::CategoryUpdate {
                name: str_field(&body, "name").map(str::to_string),
                slug: str_field(&body, "slug").map(str::to_string),
                description: field_present(&body, "description")
                    .then(|| str_field(&body, "description").map(str::to_string)),
                position: int_field(&body, "position"),
                active: bool_field(&body, "active"),
            };
            match store.update_category(id, update, now_ms()) {
                Ok(category) => json(
                    200,
                    &Value::Object(vec![("category".into(), shop::category_value(&category))]),
                ),
                Err(e) if e == "not found" => json(404, &error_value(&e)),
                Err(e) => json(400, &error_value(&e)),
            }
        }
        Method::Delete => {
            let body = body_json(req).ok();
            let query_id = query_id(req);
            let id = path_id
                .or_else(|| body.as_ref().and_then(|b| str_field(b, "id")))
                .or(query_id.as_deref());
            let Some(id) = id else {
                return json(400, &error_value("id required"));
            };
            match store.delete_category(id) {
                Ok(()) => json(200, &Value::Object(vec![("ok".into(), Value::Bool(true))])),
                Err(e) if e == "not found" => json(404, &error_value(&e)),
                Err(e) => json(400, &error_value(&e)),
            }
        }
        _ => json(405, &error_value("method not allowed")),
    }
}

fn api_cart(store: &CartStore, req: &Request, auth: &auth::State) -> Response {
    if req.method != Method::Get {
        return json(405, &error_value("method not allowed"));
    }
    let user = auth.current_user(req);
    let effective_id = user
        .as_ref()
        .map(|u| user_cart_id(&u.email))
        .or_else(|| cart::cookie_cart_id(req));
    match store.get_or_create_open(effective_id.as_deref(), now_ms()) {
        Ok((summary, created)) => {
            let set = created && user.is_none();
            cart_json(200, &summary, set)
        }
        Err(e) => json(500, &error_value(&e)),
    }
}

fn api_cart_items(
    booking_store: &BookingStore,
    shop_store: &ShopStore,
    cart_store: &CartStore,
    req: &Request,
    path_id: Option<&str>,
    auth: &auth::State,
) -> Response {
    let user = auth.current_user(req);
    let effective_id = user
        .as_ref()
        .map(|u| user_cart_id(&u.email))
        .or_else(|| cart::cookie_cart_id(req));
    let (summary, created) = match cart_store.get_or_create_open(effective_id.as_deref(), now_ms())
    {
        Ok(v) => v,
        Err(e) => return json(500, &error_value(&e)),
    };
    let set_cookie = created && user.is_none();
    match req.method {
        Method::Post => {
            let body = match body_json(req) {
                Ok(v) => v,
                Err(r) => return r,
            };
            let item = match resolve_cart_item(booking_store, shop_store, &body, now_ms()) {
                Ok(item) => item,
                Err((status, e)) => return json(status, &error_value(&e)),
            };
            match cart_store.add_item(&summary.id, item, now_ms()) {
                Ok(next) => cart_json(201, &next, set_cookie),
                Err(e) => json(400, &error_value(&e)),
            }
        }
        Method::Put | Method::Patch => {
            let body = match body_json(req) {
                Ok(v) => v,
                Err(r) => return r,
            };
            let query_id = query_id(req);
            let id = path_id
                .or_else(|| str_field(&body, "id"))
                .or(query_id.as_deref());
            let Some(id) = id else {
                return json(400, &error_value("id required"));
            };
            let Some(quantity) = int_field(&body, "quantity") else {
                return json(400, &error_value("quantity must be a non-negative number"));
            };
            match cart_store.update_quantity(&summary.id, id, quantity, now_ms()) {
                Ok(next) => cart_json(200, &next, set_cookie),
                Err(e) if e == "item not found" => json(404, &error_value(&e)),
                Err(e) => json(400, &error_value(&e)),
            }
        }
        Method::Delete => {
            let body = body_json(req).ok();
            let query_id = query_id(req);
            let id = path_id
                .or_else(|| body.as_ref().and_then(|b| str_field(b, "id")))
                .or(query_id.as_deref());
            let Some(id) = id else {
                return json(400, &error_value("id required"));
            };
            match cart_store.remove_item(&summary.id, id, now_ms()) {
                Ok(next) => cart_json(200, &next, set_cookie),
                Err(e) => json(400, &error_value(&e)),
            }
        }
        _ => json(405, &error_value("method not allowed")),
    }
}

fn api_cart_items_bulk(
    booking_store: &BookingStore,
    shop_store: &ShopStore,
    cart_store: &CartStore,
    req: &Request,
    auth: &auth::State,
) -> Response {
    if req.method != Method::Post {
        return json(405, &error_value("method not allowed"));
    }
    let body = match body_json(req) {
        Ok(v) => v,
        Err(r) => return r,
    };
    let Some(Value::Array(items)) = body.get("items") else {
        return json(400, &error_value("items[] required"));
    };
    if items.is_empty() {
        return json(400, &error_value("items[] required"));
    }
    if items.len() > 50 {
        return json(400, &error_value("too many items"));
    }
    let user = auth.current_user(req);
    let effective_id = user
        .as_ref()
        .map(|u| user_cart_id(&u.email))
        .or_else(|| cart::cookie_cart_id(req));
    let (mut summary, created) =
        match cart_store.get_or_create_open(effective_id.as_deref(), now_ms()) {
            Ok(v) => v,
            Err(e) => return json(500, &error_value(&e)),
        };
    for raw in items {
        if let Ok(item) = resolve_cart_item(booking_store, shop_store, raw, now_ms()) {
            match cart_store.add_item(&summary.id, item, now_ms()) {
                Ok(next) => summary = next,
                Err(_) => continue,
            }
        }
    }
    cart_json(201, &summary, created && user.is_none())
}

fn resolve_cart_item(
    booking_store: &BookingStore,
    shop_store: &ShopStore,
    body: &Value,
    now: i64,
) -> Result<cart::ResolvedItem, (u16, String)> {
    let item_type = str_field(body, "type").ok_or((400, "type required".to_string()))?;
    match item_type {
        "product" => {
            let ref_id = str_field(body, "refId").ok_or((400, "refId required".to_string()))?;
            let product = shop_store
                .product(ref_id)
                .filter(|p| p.active)
                .ok_or((404, "product not found".to_string()))?;
            Ok(cart::ResolvedItem {
                item_type: "product".into(),
                ref_id: product.id,
                name_snapshot: product.name,
                unit_price: product.price,
                quantity: int_field(body, "quantity").unwrap_or(1).max(1),
                metadata: Value::Object(vec![]),
            })
        }
        "gift_card" => resolve_gift_card_item(body),
        "slot" => resolve_slot_item(booking_store, body, now),
        "package" | "subscription" => resolve_snapshot_item(body, item_type),
        _ => Err((400, "invalid type".into())),
    }
}

fn resolve_gift_card_item(body: &Value) -> Result<cart::ResolvedItem, (u16, String)> {
    const MIN: i64 = 1000;
    const MAX: i64 = 500_000;
    let amount = int_field(body, "amount").ok_or((
        400,
        "Upphæð gjafabréfs verður að vera á bilinu 1.000-500.000 kr.".to_string(),
    ))?;
    if !(MIN..=MAX).contains(&amount) {
        return Err((
            400,
            "Upphæð gjafabréfs verður að vera á bilinu 1.000-500.000 kr.".into(),
        ));
    }
    let mut meta = vec![("amount".into(), Value::Int(amount))];
    for key in ["recipientName", "recipientEmail", "message", "deliveryAt"] {
        if let Some(value) = str_field(body, key).filter(|s| !s.trim().is_empty()) {
            meta.push((key.into(), Value::Str(value.trim().to_string())));
        }
    }
    Ok(cart::ResolvedItem {
        item_type: "gift_card".into(),
        ref_id: format!("gift-{}", now_ms()),
        name_snapshot: format!("Gjafabréf · {}", shop::format_isk(amount)),
        unit_price: amount,
        quantity: 1,
        metadata: Value::Object(meta),
    })
}

fn resolve_slot_item(
    booking_store: &BookingStore,
    body: &Value,
    now: i64,
) -> Result<cart::ResolvedItem, (u16, String)> {
    let ref_id = str_field(body, "refId").ok_or((400, "refId required".to_string()))?;
    let slot_ms = booking::time::parse_instant(ref_id).ok_or((400, "invalid slot".to_string()))?;
    if slot_ms < now {
        return Err((400, "slot is in the past".into()));
    }
    let day = booking::time::day_start(slot_ms);
    let available = booking_store
        .availability(day, 1, None, now)
        .iter()
        .flat_map(|d| d.slots.iter())
        .find(|s| s.starts_at == ref_id)
        .map(|s| s.status == "available")
        .unwrap_or(false);
    if !available {
        return Err((409, "slot already booked".into()));
    }
    let hour = booking::time::hour_of(slot_ms);
    Ok(cart::ResolvedItem {
        item_type: "slot".into(),
        ref_id: ref_id.to_string(),
        name_snapshot: format!("{ref_id} kl. {hour:02}:00"),
        unit_price: booking_store.slot_price(hour, None),
        quantity: 1,
        metadata: Value::Object(vec![
            ("startsAt".into(), Value::Str(ref_id.to_string())),
            ("hour".into(), Value::Int(hour)),
        ]),
    })
}

fn resolve_snapshot_item(
    body: &Value,
    item_type: &str,
) -> Result<cart::ResolvedItem, (u16, String)> {
    let ref_id = str_field(body, "refId").ok_or((400, "refId required".to_string()))?;
    let name = str_field(body, "nameSnapshot")
        .or_else(|| str_field(body, "name"))
        .ok_or((400, "nameSnapshot required".to_string()))?;
    let unit_price = int_field(body, "unitPrice")
        .or_else(|| int_field(body, "price"))
        .ok_or((400, "unitPrice required".to_string()))?;
    Ok(cart::ResolvedItem {
        item_type: item_type.to_string(),
        ref_id: ref_id.to_string(),
        name_snapshot: name.trim().to_string(),
        unit_price,
        quantity: if item_type == "subscription" {
            1
        } else {
            int_field(body, "quantity").unwrap_or(1).max(1)
        },
        metadata: body
            .get("metadata")
            .cloned()
            .unwrap_or_else(|| Value::Object(vec![])),
    })
}

/// Derive a stable, valid cart ID for an authenticated user.
/// Uses the email with non-alphanumeric chars mapped to dashes so it satisfies
/// `cart::valid_cart_id` (alphanumeric + dash, max 96 chars).
fn user_cart_id(email: &str) -> String {
    let slug: String = email
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
        .collect::<String>()
        .trim_matches('-')
        .to_string();
    format!("u-{}", &slug[..slug.len().min(90)])
}

fn cart_json(status: u16, summary: &cart::CartSummary, set_cookie: bool) -> Response {
    let resp = json(
        status,
        &Value::Object(vec![("cart".into(), cart::cart_value(summary))]),
    );
    if set_cookie {
        resp.with_header("Set-Cookie", &cart::cookie_header(&summary.id))
    } else {
        resp
    }
}

fn product_values(store: &ShopStore, active_only: bool) -> Vec<Value> {
    store
        .list_products(active_only)
        .iter()
        .map(|p| shop::product_value(p, store.category_name(p.category_id.as_deref())))
        .collect()
}

fn body_json(req: &Request) -> Result<Value, Response> {
    akurai_json::parse(&req.body_str()).map_err(|_| json(400, &error_value("invalid JSON body")))
}

fn str_field<'a>(body: &'a Value, key: &str) -> Option<&'a str> {
    body.get(key)
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|s| !s.is_empty())
}

fn int_field(body: &Value, key: &str) -> Option<i64> {
    match body.get(key)? {
        Value::Int(n) => Some(*n),
        Value::Float(n) if n.is_finite() => Some(n.floor() as i64),
        _ => None,
    }
}

fn bool_field(body: &Value, key: &str) -> Option<bool> {
    body.get(key).and_then(Value::as_bool)
}

fn field_present(body: &Value, key: &str) -> bool {
    matches!(body, Value::Object(pairs) if pairs.iter().any(|(k, _)| k == key))
}

fn query_id(req: &Request) -> Option<String> {
    field(&query_pairs(req), "id")
        .filter(|s| !s.is_empty())
        .map(str::to_string)
}

// ---- content pages --------------------------------------------------------

fn news_list(root: &Path, auth: &auth::State, req: &Request) -> Response {
    let items = content::news_items(&content_dir(root));
    render(
        root,
        "frettir",
        vec![
            ("page_title".into(), Value::Str("Fréttir".into())),
            ("news".into(), Value::Array(items)),
        ],
        auth,
        req,
    )
}

fn news_detail(root: &Path, slug: &str, auth: &auth::State, req: &Request) -> Response {
    if !valid_slug(slug) {
        return not_found_page(root, auth, req);
    }
    let path = content_dir(root).join("frettir").join(format!("{slug}.md"));
    article(root, &path, "Fréttir", auth, req)
}

fn handbook_list(root: &Path, auth: &auth::State, req: &Request) -> Response {
    let chapters = content::handbook_chapters(&content_dir(root));
    render(
        root,
        "notendahandbok",
        vec![
            ("page_title".into(), Value::Str("Notendahandbók".into())),
            ("chapters".into(), Value::Array(chapters)),
        ],
        auth,
        req,
    )
}

fn handbook_detail(root: &Path, slug: &str, auth: &auth::State, req: &Request) -> Response {
    if !valid_slug(slug) {
        return not_found_page(root, auth, req);
    }
    let path = content_dir(root)
        .join("notendahandbok")
        .join(format!("{slug}.md"));
    article(root, &path, "Notendahandbók", auth, req)
}

fn legal(root: &Path, name: &str, auth: &auth::State, req: &Request) -> Response {
    let path = content_dir(root).join("legal").join(format!("{name}.md"));
    article(root, &path, "", auth, req)
}

fn about(root: &Path, auth: &auth::State, req: &Request) -> Response {
    let path = content_dir(root).join("um-okkur.md");
    article(root, &path, "", auth, req)
}

// ---- account (mínar síður) page -------------------------------------------

/// `GET /my` — the signed-in user's account dashboard.
///
/// Server-side auth gate: unauthenticated requests redirect to `/login` (the
/// page's own JS performs the same `/api/me` 401 → `/login` redirect once
/// loaded, but the server gate means an unauthenticated `curl /my` never even
/// renders the shell).
///
/// The user's **active subscriptions** are server-rendered here (their daily
/// limit + validity window), because the account page is the only consumer and
/// there is no standalone subscriptions API yet. Profile, packages, and bookings
/// are fetched client-side from `/api/me`, `/api/user-packages`, and
/// `/api/bookings`. A subscription is *active* when today's calendar day falls
/// inside its `[valid_from, valid_until]` window (see [`booking::subscription`]).
fn my_page(root: &Path, store: &BookingStore, auth: &auth::State, req: &Request) -> Response {
    let Some(user) = auth.current_user(req) else {
        return Response::new(302).with_header("Location", "/login");
    };

    let now = now_ms();
    let mut subs: Vec<Value> = Vec::new();
    let mut active_count = 0_i64;
    for sub in store.user_subscriptions_for_user(&user.email) {
        let is_active = booking::subscription::covers_date(sub.valid_from, sub.valid_until, now);
        if is_active {
            active_count += 1;
        }
        subs.push(Value::Object(vec![
            ("id".into(), Value::Str(sub.id)),
            ("isActive".into(), Value::Bool(is_active)),
            ("dailyLimit".into(), Value::Int(sub.daily_limit)),
            (
                "validFrom".into(),
                Value::Str(booking::time::date_string(sub.valid_from)),
            ),
            (
                "validUntil".into(),
                Value::Str(booking::time::date_string(sub.valid_until)),
            ),
        ]));
    }

    render(
        root,
        "my",
        vec![
            (
                "page_title".into(),
                Value::Str("Mínar síður — Golfsetrið Akureyri".into()),
            ),
            ("subscriptions".into(), Value::Array(subs)),
            ("active_subscriptions_count".into(), Value::Int(active_count)),
        ],
        auth,
        req,
    )
}

// ---- shop + cart pages ----------------------------------------------------

fn shop_page(root: &Path, store: &ShopStore, auth: &auth::State, req: &Request) -> Response {
    render(
        root,
        "shop",
        vec![
            (
                "page_title".into(),
                Value::Str("Verslun — Golfsetrið Akureyri".into()),
            ),
            ("products".into(), Value::Array(product_values(store, true))),
            (
                "categories".into(),
                Value::Array(
                    store
                        .list_categories(false)
                        .iter()
                        .map(shop::category_value)
                        .collect(),
                ),
            ),
        ],
        auth,
        req,
    )
}

fn cart_page(root: &Path, store: &CartStore, req: &Request, auth: &auth::State) -> Response {
    let user = auth.current_user(req);
    let effective_id = user
        .as_ref()
        .map(|u| user_cart_id(&u.email))
        .or_else(|| cart::cookie_cart_id(req));
    match store.get_or_create_open(effective_id.as_deref(), now_ms()) {
        Ok((summary, created)) => {
            let mut resp = render(
                root,
                "cart",
                vec![
                    (
                        "page_title".into(),
                        Value::Str("Karfan — Golfsetrið Akureyri".into()),
                    ),
                    ("cart".into(), cart::cart_value(&summary)),
                    (
                        "subtotal_label".into(),
                        Value::Str(shop::format_isk(summary.subtotal)),
                    ),
                    ("has_items".into(), Value::Bool(!summary.items.is_empty())),
                ],
                auth,
                req,
            );
            if created && user.is_none() {
                resp = resp.with_header("Set-Cookie", &cart::cookie_header(&summary.id));
            }
            resp
        }
        Err(e) => json(500, &error_value(&e)),
    }
}

fn admin_products_page(
    root: &Path,
    store: &ShopStore,
    auth: &auth::State,
    req: &Request,
) -> Response {
    render(
        root,
        "admin_products",
        vec![
            ("page_title".into(), Value::Str("Vörur — Stjórnborð".into())),
            (
                "products".into(),
                Value::Array(product_values(store, false)),
            ),
        ],
        auth,
        req,
    )
}

fn admin_categories_page(
    root: &Path,
    store: &ShopStore,
    auth: &auth::State,
    req: &Request,
) -> Response {
    render(
        root,
        "admin_categories",
        vec![
            (
                "page_title".into(),
                Value::Str("Flokkar — Stjórnborð".into()),
            ),
            (
                "categories".into(),
                Value::Array(
                    store
                        .list_categories(false)
                        .iter()
                        .map(shop::category_value)
                        .collect(),
                ),
            ),
        ],
        auth,
        req,
    )
}

fn admin_product_form_page(
    root: &Path,
    store: &ShopStore,
    id: Option<&str>,
    auth: &auth::State,
    req: &Request,
) -> Response {
    let product = match id {
        Some(id) => match store.product(id) {
            Some(product) => Some(product),
            None => return not_found_page(root, auth, req),
        },
        None => None,
    };
    let selected = product.as_ref().and_then(|p| p.category_id.as_deref());
    let categories = store
        .list_categories(false)
        .iter()
        .map(|c| {
            let mut value = match shop::category_value(c) {
                Value::Object(pairs) => pairs,
                _ => vec![],
            };
            value.push((
                "selected".into(),
                Value::Bool(selected == Some(c.id.as_str())),
            ));
            Value::Object(value)
        })
        .collect();
    let product_value = product
        .as_ref()
        .map(|p| shop::product_value(p, store.category_name(p.category_id.as_deref())))
        .unwrap_or_else(|| {
            Value::Object(vec![
                ("id".into(), Value::Str(String::new())),
                ("name".into(), Value::Str(String::new())),
                ("description".into(), Value::Str(String::new())),
                ("price".into(), Value::Str(String::new())),
                ("imageUrl".into(), Value::Str(String::new())),
                ("categoryId".into(), Value::Str(String::new())),
                ("active".into(), Value::Bool(true)),
            ])
        });
    let is_edit = product.is_some();
    render(
        root,
        "admin_product_form",
        vec![
            (
                "page_title".into(),
                Value::Str(if is_edit {
                    "Breyta vöru — Stjórnborð".into()
                } else {
                    "Ný vara — Stjórnborð".into()
                }),
            ),
            ("product".into(), product_value),
            ("categories".into(), Value::Array(categories)),
            ("is_edit".into(), Value::Bool(is_edit)),
            (
                "form_title".into(),
                Value::Str(if is_edit { "Breyta vöru" } else { "Ný vara" }.into()),
            ),
        ],
        auth,
        req,
    )
}

// ---- booking calendar page ------------------------------------------------

/// Short Icelandic weekday names (`Date.getDay()` order, 0 = Sunday), mirroring
/// the source `DAY_NAMES`.
const DAY_NAMES: [&str; 7] = ["Sun", "Mán", "Þri", "Mið", "Fim", "Fös", "Lau"];

/// Render the home booking calendar: availability + pricing across the booking
/// window (14 days for an anonymous visitor, mirroring `getBookingWindowEnd`).
/// Server-rendered — the slots are plain links/markup, no client JS required.
fn calendar_page(root: &Path, store: &BookingStore, auth: &auth::State, req: &Request) -> Response {
    let now = now_ms();
    let start = booking::time::day_start(now);
    let days = 14; // anonymous default window
    let availability = store.availability(start, days, None, now);

    let day_values: Vec<Value> = availability
        .iter()
        .map(|day| {
            let weekday = booking::time::parse_date(&day.date)
                .map(|ms| DAY_NAMES[booking::time::weekday_index(ms)])
                .unwrap_or("");
            let slots: Vec<Value> = day
                .slots
                .iter()
                .map(|s| {
                    Value::Object(vec![
                        ("hour_label".into(), Value::Str(format!("{:02}:00", s.hour))),
                        ("price_label".into(), Value::Str(format_isk(s.price))),
                        ("status".into(), Value::Str(s.status.clone())),
                        ("available".into(), Value::Bool(s.status == "available")),
                        ("starts_at".into(), Value::Str(s.starts_at.clone())),
                    ])
                })
                .collect();
            Value::Object(vec![
                ("date".into(), Value::Str(day.date.clone())),
                ("weekday".into(), Value::Str(weekday.into())),
                ("slots".into(), Value::Array(slots)),
            ])
        })
        .collect();

    let legend: Vec<Value> = store
        .active_pricing_rules()
        .iter()
        .map(|r| {
            Value::Object(vec![
                ("name".into(), Value::Str(r.name.clone())),
                (
                    "range_label".into(),
                    Value::Str(format!("{:02}:00–{:02}:00", r.start_hour, r.end_hour)),
                ),
                ("price_label".into(), Value::Str(format_isk(r.price))),
            ])
        })
        .collect();

    render(
        root,
        "calendar",
        vec![
            (
                "page_title".into(),
                Value::Str("Bókaðu rástíma — Golfsetrið Akureyri".into()),
            ),
            ("calendar_days".into(), Value::Array(day_values)),
            ("pricing_legend".into(), Value::Array(legend)),
        ],
        auth,
        req,
    )
}

/// Format an ISK amount with thousands separators and a `kr` suffix, matching
/// the source's `formatPrice` (e.g. `3500` → `3.500 kr`).
fn format_isk(amount: i64) -> String {
    let neg = amount < 0;
    let digits = amount.unsigned_abs().to_string();
    let mut out = String::new();
    let len = digits.len();
    for (i, ch) in digits.chars().enumerate() {
        if i > 0 && (len - i).is_multiple_of(3) {
            out.push('.');
        }
        out.push(ch);
    }
    format!("{}{} kr", if neg { "-" } else { "" }, out)
}

/// Render a single markdown article into the `article` template. The frontmatter
/// `title`/`date`/`lead`/`lastUpdated` populate the page; the body is converted
/// to HTML by `akurai_markdown`. A missing file renders the 404 page.
fn article(
    root: &Path,
    md_path: &Path,
    section: &str,
    auth: &auth::State,
    req: &Request,
) -> Response {
    let raw = match fs::read_to_string(md_path) {
        Ok(text) => text,
        Err(_) => return not_found_page(root, auth, req),
    };
    let doc = content::parse(&raw);
    let body_html = akurai_markdown::to_html(&doc.body);
    let title = doc.get("title").unwrap_or(section).to_string();

    let mut extra = vec![
        ("page_title".into(), Value::Str(title.clone())),
        ("title_text".into(), Value::Str(title)),
        ("section".into(), Value::Str(section.to_string())),
        ("content".into(), Value::Str(body_html)),
    ];
    if let Some(date) = doc.get("date") {
        extra.push(("date".into(), Value::Str(date.to_string())));
    }
    if let Some(lead) = doc.get("lead") {
        extra.push(("lead".into(), Value::Str(lead.to_string())));
    }
    if let Some(updated) = doc.get("lastUpdated") {
        extra.push(("last_updated".into(), Value::Str(updated.to_string())));
    }
    if let Some(desc) = doc.get("metaDescription") {
        extra.push(("meta_description".into(), Value::Str(desc.to_string())));
    }
    render(root, "article", extra, auth, req)
}

// ---- declarative routed pages (home + placeholders) -----------------------

/// A resolved route: which template to render and an optional `backend/`-relative
/// JSON data file to merge into the context.
struct RouteDef {
    template: String,
    data: Option<String>,
    title: Option<String>,
}

fn render_page_routed(root: &Path, path: &str, auth: &auth::State, req: &Request) -> Response {
    match load_routes(root) {
        Some(router) => match router.match_path(path) {
            Some(m) => render_routed(root, m.value, &m.params, auth, req),
            None => not_found_page(root, auth, req),
        },
        None => not_found_page(root, auth, req),
    }
}

fn render_routed(
    root: &Path,
    def: &RouteDef,
    params: &[(String, String)],
    auth: &auth::State,
    req: &Request,
) -> Response {
    let mut extra: Vec<(String, Value)> = Vec::new();

    // Per-route data file: spread its top-level object keys into the context
    // (the framework's data-loader convention), skipping the reserved `params`.
    if let Some(rel) = &def.data {
        if let Some(Value::Object(pairs)) = load_route_data(root, rel) {
            for (k, v) in pairs {
                if k != "params" {
                    extra.push((k, v));
                }
            }
        }
    }

    // Page title: a `heading` from the data file wins, else the route's SEO title.
    let page_title = extra
        .iter()
        .find(|(k, _)| k == "heading")
        .and_then(|(_, v)| v.as_str().map(str::to_string))
        .or_else(|| def.title.clone());
    if let Some(title) = page_title {
        extra.push(("page_title".into(), Value::Str(title)));
    }

    extra.push(("params".into(), params_value(params)));
    render(root, &def.template, extra, auth, req)
}

/// Load `backend/routes.json` into a router. Mirrors the framework's `routes.rs`
/// but only reads the fields this app uses (`template`, `data`, `title`).
fn load_routes(root: &Path) -> Option<Router<RouteDef>> {
    let path = root.parent()?.join("backend/routes.json");
    let text = fs::read_to_string(path).ok()?;
    let value = akurai_json::parse(&text).ok()?;
    let Value::Array(entries) = value.get("routes")? else {
        return None;
    };
    let mut router = Router::new();
    let mut any = false;
    for entry in entries {
        if let (Some(pattern), Some(template)) = (
            entry.get("path").and_then(Value::as_str),
            entry.get("template").and_then(Value::as_str),
        ) {
            router.route(
                pattern,
                RouteDef {
                    template: template.to_string(),
                    data: entry.get("data").and_then(Value::as_str).map(String::from),
                    title: entry.get("title").and_then(Value::as_str).map(String::from),
                },
            );
            any = true;
        }
    }
    any.then_some(router)
}

/// Load and parse a `backend/`-relative JSON data file, rejecting path traversal.
fn load_route_data(root: &Path, rel: &str) -> Option<Value> {
    let rel = rel.trim_start_matches('/');
    if rel.is_empty() || rel.split('/').any(|seg| seg == ".." || seg == ".") {
        return None;
    }
    let path = root.parent()?.join("backend").join(rel);
    let text = fs::read_to_string(path).ok()?;
    akurai_json::parse(&text).ok()
}

fn params_value(params: &[(String, String)]) -> Value {
    Value::Object(
        params
            .iter()
            .map(|(k, v)| (k.clone(), Value::Str(v.clone())))
            .collect(),
    )
}

// ---- rendering core -------------------------------------------------------

/// Render template `name` with the `page.json` context plus `extra` pairs. A
/// template or parse error surfaces as a 500 so it is visible in development.
fn render(
    root: &Path,
    name: &str,
    mut extra: Vec<(String, Value)>,
    auth: &auth::State,
    req: &Request,
) -> Response {
    let engine = match build_engine(root) {
        Ok(engine) => engine,
        Err(msg) => return Response::new(500).with_html(&error_page(&msg)),
    };
    // Inject the signed-in user email for the header nav.
    if let Some(user) = auth.current_user(req) {
        extra.push(("auth_user_email".into(), Value::Str(user.email)));
    }
    let mut context = load_context(root);
    if let Value::Object(pairs) = &mut context {
        pairs.extend(extra);
    }
    match engine.render(name, &context) {
        Ok(html) => with_no_cache(Response::ok().with_html(&html)),
        Err(e) => Response::new(500).with_html(&error_page(&e.message)),
    }
}

/// Render the 404 page (status 404). Falls back to a bare body if the template
/// itself is missing or broken.
fn not_found_page(root: &Path, auth: &auth::State, req: &Request) -> Response {
    let mut resp = render(
        root,
        "notfound",
        vec![("page_title".into(), Value::Str("Síða finnst ekki".into()))],
        auth,
        req,
    );
    if resp.status == 200 {
        resp.status = 404;
    }
    resp
}

/// Register every `frontend/*.html` as a template keyed by file stem.
fn build_engine(root: &Path) -> Result<Engine, String> {
    let mut engine = Engine::new();
    let entries = fs::read_dir(root).map_err(|e| format!("cannot read {}: {e}", root.display()))?;
    for entry in entries {
        let path = entry.map_err(|e| e.to_string())?.path();
        if path.extension().and_then(|e| e.to_str()) != Some("html") {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        let source = fs::read_to_string(&path).map_err(|e| e.to_string())?;
        engine
            .register(stem, &source)
            .map_err(|e| format!("{stem}.html: {}", e.message))?;
    }
    Ok(engine)
}

/// Load the shared page context from `backend/page.json`, or an empty object.
fn load_context(root: &Path) -> Value {
    let empty = Value::Object(vec![]);
    let Some(path) = root.parent().map(|p| p.join("backend/page.json")) else {
        return empty;
    };
    match fs::read_to_string(&path) {
        Ok(text) => akurai_json::parse(&text).unwrap_or(empty),
        Err(_) => empty,
    }
}

/// The project's `content/` dir, a sibling of `frontend/`.
fn content_dir(root: &Path) -> PathBuf {
    root.parent()
        .map(|p| p.join("content"))
        .unwrap_or_else(|| root.join("content"))
}

// ---- static assets + CSS engine -------------------------------------------

/// Generate `utilities.css` by scanning frontend source for utility classes.
fn utilities(root: &Path) -> Response {
    let mut files = Vec::new();
    collect_sources(root, &mut files);
    files.sort();
    let sources: Vec<String> = files
        .iter()
        .filter_map(|p| fs::read_to_string(p).ok())
        .collect();
    let refs: Vec<&str> = sources.iter().map(String::as_str).collect();
    let css = akurai_css::build(&refs);
    with_no_cache(Response::ok().with_body("text/css; charset=utf-8", css.into_bytes()))
}

/// Recursively collect scannable frontend source files (HTML/JS) under `dir`.
fn collect_sources(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let Ok(meta) = entry.metadata() else { continue };
        if meta.is_dir() {
            collect_sources(&path, out);
        } else if matches!(
            path.extension().and_then(|e| e.to_str()),
            Some("html") | Some("htm") | Some("js") | Some("mjs")
        ) {
            out.push(path);
        }
    }
}

fn serve_static(root: &Path, req_path: &str) -> Response {
    match resolve(root, req_path) {
        Some(path) if path.is_file() => match fs::read(&path) {
            Ok(bytes) => with_no_cache(
                Response::ok().with_body(mime::for_path(&path.to_string_lossy()), bytes),
            ),
            Err(_) => Response::not_found(),
        },
        _ => Response::not_found(),
    }
}

/// Map a request path to a file under `root`, rejecting traversal (`..`/`.`).
fn resolve(root: &Path, req_path: &str) -> Option<PathBuf> {
    let rel = req_path.trim_start_matches('/');
    let rel = if rel.is_empty() { "index.html" } else { rel };
    if rel.split('/').any(|seg| seg == ".." || seg == ".") {
        return None;
    }
    Some(root.join(rel))
}

/// A request is a static asset if its last segment has a non-`.html` extension.
fn is_static_asset(path: &str) -> bool {
    let last = path.rsplit('/').next().unwrap_or("");
    match last.rsplit_once('.') {
        Some((_, ext)) => !ext.eq_ignore_ascii_case("html"),
        None => false,
    }
}

// ---- helpers --------------------------------------------------------------

/// Extract a single-segment slug after `prefix` (drops a trailing slash).
fn slug_of<'a>(path: &'a str, prefix: &str) -> &'a str {
    path.strip_prefix(prefix)
        .unwrap_or("")
        .trim_end_matches('/')
}

/// A safe content slug: non-empty, no path separators, ASCII word/`-` only.
fn valid_slug(slug: &str) -> bool {
    !slug.is_empty()
        && slug
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
}

fn with_no_cache(resp: Response) -> Response {
    resp.with_header("Cache-Control", NO_CACHE)
}

fn json(status: u16, value: &Value) -> Response {
    Response::new(status).with_body(
        "application/json; charset=utf-8",
        value.to_json().into_bytes(),
    )
}

/// `GET /api/me` — current user profile.
fn api_me(auth: &auth::State, req: &Request) -> Response {
    if req.method != Method::Get {
        return json(405, &error_value("method not allowed"));
    }
    let Some(user) = auth.current_user(req) else {
        return json(401, &error_value("Unauthorized"));
    };
    let profile = Value::Object(vec![
        ("id".into(), Value::Str(user.email.clone())),
        ("email".into(), Value::Str(user.email)),
        ("role".into(), Value::Str(user.role.as_str().into())),
    ]);
    json(200, &Value::Object(vec![("user".into(), profile)]))
}

/// `GET /api/user-packages` — user's packages with remaining slots.
fn api_user_packages(store: &BookingStore, auth: &auth::State, req: &Request) -> Response {
    if req.method != Method::Get {
        return json(405, &error_value("method not allowed"));
    }
    let Some(user) = auth.current_user(req) else {
        return json(401, &error_value("Unauthorized"));
    };
    let packages = store.user_packages_for_user(&user.email);
    let pkg_values: Vec<Value> = packages
        .into_iter()
        .map(|p| {
            Value::Object(vec![
                ("id".into(), Value::Str(p.id)),
                (
                    "name".into(),
                    p.package_name
                        .map(Value::Str)
                        .unwrap_or(Value::Str("Unknown".into())),
                ),
                (
                    "slotCount".into(),
                    p.slot_count.map(Value::Int).unwrap_or(Value::Int(0)),
                ),
                ("remaining".into(), Value::Int(p.remaining)),
            ])
        })
        .collect();
    json(
        200,
        &Value::Object(vec![("packages".into(), Value::Array(pkg_values))]),
    )
}

fn health() -> Value {
    Value::Object(vec![
        ("app".into(), Value::Str("golfsetridak".into())),
        ("framework".into(), Value::Str("AkurAI-Framework".into())),
        ("version".into(), Value::Str(VERSION.into())),
        ("status".into(), Value::Str("ok".into())),
    ])
}

fn error_value(message: &str) -> Value {
    Value::Object(vec![("error".into(), Value::Str(message.into()))])
}

fn error_page(message: &str) -> String {
    let mut escaped = String::new();
    for c in message.chars() {
        match c {
            '<' => escaped.push_str("&lt;"),
            '>' => escaped.push_str("&gt;"),
            '&' => escaped.push_str("&amp;"),
            c => escaped.push(c),
        }
    }
    format!(
        "<!doctype html><meta charset=utf-8><title>Template error</title>\
         <body style=\"font:16px system-ui;background:#0a0f0c;color:#ff6b6b;padding:40px\">\
         <h1>Template error</h1><pre style=\"color:#e9efe9\">{escaped}</pre></body>"
    )
}

// ---------------------------------------------------------------------------
// Public helpers for the auth module
// ---------------------------------------------------------------------------

/// Build the template engine from `root`. Called by `auth` to render login.
pub fn build_engine_pub(root: &Path) -> Result<akurai_template::Engine, String> {
    build_engine(root)
}

/// Load `backend/page.json` context. Called by `auth` to merge site globals.
pub fn load_context_pub(root: &Path) -> Value {
    load_context(root)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn slug_extraction_and_validation() {
        assert_eq!(slug_of("/frettir/abc-1", "/frettir/"), "abc-1");
        assert_eq!(slug_of("/frettir/abc/", "/frettir/"), "abc");
        assert!(valid_slug("6-7-payday-bokhald-og-vsk"));
        assert!(!valid_slug(""));
        assert!(!valid_slug("../etc/passwd"));
        assert!(!valid_slug("a/b"));
    }

    #[test]
    fn static_asset_detection() {
        assert!(is_static_asset("/styles.css"));
        assert!(is_static_asset("/img/logo.svg"));
        assert!(!is_static_asset("/frettir"));
        assert!(!is_static_asset("/index.html"));
    }

    #[test]
    fn resolve_rejects_traversal() {
        assert!(resolve(Path::new("/srv"), "/../../etc/passwd").is_none());
        assert!(resolve(Path::new("/srv"), "/ok/app.js").is_some());
        assert!(resolve(Path::new("/srv"), "/")
            .unwrap()
            .ends_with("index.html"));
    }

    #[test]
    fn route_data_rejects_traversal() {
        assert!(load_route_data(Path::new("/srv/frontend"), "../secrets.json").is_none());
        assert!(load_route_data(Path::new("/srv/frontend"), "").is_none());
        assert!(load_route_data(Path::new("/srv/frontend"), "data/missing.json").is_none());
    }

    #[test]
    fn health_reports_ok() {
        let v = health();
        assert_eq!(v.get("status").and_then(Value::as_str), Some("ok"));
        assert_eq!(v.get("app").and_then(Value::as_str), Some("golfsetridak"));
    }
}
